#!/bin/bash
# Selective pull: only cherry-pick 60.1.0 / 6100 files into product/
# Run from site root: /var/www/www-root/data/www/boybio.net
set -euo pipefail
cd "$(dirname "$0")"
REPO_ROOT="${1:-.}"
cd "$REPO_ROOT"

git fetch origin backup

LIST=(
  "product/app/controllers/AccountPayments.php"
  "product/app/controllers/admin/AdminCreditNotes.php"
  "product/app/controllers/admin/AdminPaymentCreate.php"
  "product/app/controllers/admin/AdminPaymentProcessors.php"
  "product/app/controllers/admin/AdminPayments.php"
  "product/app/controllers/admin/AdminSettings.php"
  "product/app/controllers/admin/AdminTaxesImport.php"
  "product/app/controllers/admin/AdminTaxes.php"
  "product/app/controllers/admin/AdminUserUpdate.php"
  "product/app/controllers/CreditNotes.php"
  "product/app/controllers/Invoice.php"
  "product/app/controllers/PayBilling.php"
  "product/app/controllers/PaymentProcessorCreate.php"
  "product/app/controllers/PaymentProcessorUpdate.php"
  "product/app/controllers/Pay.php"
  "product/app/controllers/WebhookKlarna.php"
  "product/app/controllers/WebhookPaddleBilling.php"
  "product/app/controllers/WebhookPaddle.php"
  "product/app/controllers/WebhookPlisio.php"
  "product/app/controllers/WebhookPlisioWhitelabel.php"
  "product/app/controllers/WebhookRevolut.php"
  "product/app/core/Router.php"
  "product/app/helpers/payment-gateways/Paddle.php"
  "product/app/helpers/payment-gateways/Plisio.php"
  "product/app/helpers/payment-gateways/Revolut.php"
  "product/app/includes/available_plan_features.php"
  "product/app/includes/payment_processors.php"
  "product/app/includes/plisio_cryptocurrencies.php"
  "product/app/languages/admin/english#en.php"
  "product/app/languages/english#en.php"
  "product/app/models/PaymentProcessor.php"
  "product/app/models/Payments.php"
  "product/themes/altum/views/admin/credit-notes/index.php"
  "product/themes/altum/views/admin/payments/admin_payment_dropdown_button.php"
  "product/themes/altum/views/admin/payments/index.php"
  "product/themes/altum/views/admin/payments/payment_approve_modal.php"
  "product/themes/altum/views/admin/payments/payment_cancel_modal.php"
  "product/themes/altum/views/admin/payments/payment_refund_modal.php"
  "product/themes/altum/views/admin/settings/partials/klarna.php"
  "product/themes/altum/views/admin/settings/partials/paddle_billing.php"
  "product/themes/altum/views/admin/settings/partials/payment.php"
  "product/themes/altum/views/admin/settings/partials/plisio.php"
  "product/themes/altum/views/admin/settings/partials/plisio_whitelabel.php"
  "product/themes/altum/views/admin/settings/partials/paddle.php"
  "product/themes/altum/views/admin/settings/partials/revolut.php"
  "product/themes/altum/views/credit-notes/index.php"
  "product/themes/altum/views/pay/index.php"
  "product/themes/altum/views/pay/plisio_whitelabel_modal.php"
  "product/update/info.php"
  "product/update/sql/6100.sql"
  "product/FINAL_READY.sql"
  "pull-cherry-pick-6100.sh"
)

echo "Checking out ${#LIST[@]} paths from origin/backup ..."
git checkout origin/backup -- "${LIST[@]}"
echo "Done. Run /update/ or FINAL_READY.sql on DB, then clear cache."
